### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by cannox227** [tollsimy/lexibot#2]
- [ ] Ask for arguments after launching a command, e.g. 
  1. /start 
  2. bot output prompt waiting for arguments
  3. parsing arguments
- [x] Random word to test the user knowledge of the languages
- [x] Handle properly Upper/Lower case in set sheet
- [ ] Fix messed up code

**Comment by tollsimy** [comment]
1. [ ] Fix crash when sh var is NoneType (example /printall without sheet created)
2. [ ] Change "resume [id]" to "resume [link]" on bot msg
3. [ ] Check inverted target lang - mother tongue lang when printing words from sheet
4. [ ] Add check with result after /random command to help user know if the guess was right or wrong
5. [ ] Add translation of expressions
6. [ ] Add /translate to insert a word/expression in target language
